[book]
authors = ["Lenny Peng"]
language = "zh"
multilingual = false
src = "src"
title = "Yet another Chinese Head First Java book."
description = "《Head First Java》 中文版，Yet another Chinese Head First Java book."

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]


[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/gnu4cn/learningJava"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[output.html.search]
enable = false
